In [2]:
import numpy as np

In [ ]:
# how to create a array in numpy
a1 = np.array([1,2,3,4,5]) # vector
a1

array([1, 2, 3, 4, 5])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a1.ndim

1

In [11]:
# matric
a2 = np.array([[1,2,3],[4,5,6]]) # 2d
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a2.ndim

2

In [12]:
# tensor --> 3d or more then 3d
a3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3d
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [13]:
a3.ndim

3

In [ ]:
a1.shape # rows x columns

(5,)

In [15]:
a1

array([1, 2, 3, 4, 5])

In [16]:
a2.shape

(2, 3)

In [17]:
a2


array([[1, 2, 3],
       [4, 5, 6]])